# Generated by Django 2.1 on 2018-08-23 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180822_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('view_all_borrow', 'View all borrowed books'),)},
        ),
    ]
