# Generated by Django 2.1 on 2018-08-23 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180823_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('view_all_borrow', 'View all borrowed books'), ('can_renew_book', 'Renew a book'))},
        ),
    ]
