# Generated by Django 2.1 on 2018-08-23 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180823_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', '-pubdate'], 'permissions': (('can_create_book', 'Add new books'), ('can_update_book', 'Update book details'), ('can_delete_book', 'Delete books'))},
        ),
    ]
